### ISSUE TITLE
UCMACM Website v2

### ISSUE THREAD

**Issue by No767** [UCMercedACM/Chapter-Website#258]
## Introduction

For the last semester, the project has been constantly held back, delayed, and shown many issues due to an aging codebase. Essentially no work was able to be done due to years of technical debt, near zero documentation, broken code, and focusing on the wrong target. This issue aims to bring a comprehensive roadmap of what's expected.

Please note that this is not a complete list, and may change at any time.

## Contributing

The first task is to join the [UCMACM discord server](https://discord.gg/4pHjfmK), and ask me or one of the project leads. Discussions take place under `#acm-website`, and will be used to help aid in the direction or guidance of the project. In addition, you must also read the [onboarding guide](https://ucmacm-website.readthedocs.io/en/latest/onboarding/index.html) if you are starting off for the first time

Once you have discussed your contribution, open a PR. **The pull request should target `react-rewrite`, not any other branches**.

## Roadmap

Below is a roadmap detailing the parts of the eventual website:

### Frontend

- [x] New Figma design based on [NextUI](https://nextui.org/)
- [x] Rebuild front landing page (#259)
    - Uses the NextUI library
    - [x] Website Components
        - Navbar
        - Footer
        - Front landing header
        - Better about us
        - SIGs introduction
- [ ] Rebuild other pages
    - [ ] SIGs (#279)
    - [ ] Events
- [ ] Design web dashboard
- [x] Login page for dashboard
- [ ] Project showcase (#227)

### Backend

- [ ] Create a `utils` package to use within the frontend
- [x] Move away from Firebase and use a different service instead for backend storage (Will be Supabase)
- [x] Consider hosting options (Vercel and Supabase)
- [ ] Deploy development dbs, staging, internal POP dbs, production db
- [x] Look into cost of hosting Supabase / Infra usage costs

**Comment by No767** [comment]
See Basecamp for roadmap
